---
- name: Pull images from staging registry via CLI
  become: true
  ansible.builtin.shell: |
    set -e
    if [ -z "{{ registry_ip }}" ] || [ -z "{{ registry_port }}" ] || [ -z "{{ image_tag }}" ]; then
      echo "❌ One or more required variables are undefined: registry_ip, registry_port, image_tag"
      exit 1
    fi
    echo "Pulling image: {{ registry_ip }}:{{ registry_port }}/{{ item.name }}:{{ image_tag }}"
    docker pull {{ registry_ip }}:{{ registry_port }}/{{ item.name }}:{{ image_tag }}
  loop:
    - { name: "healthify-frontend" }
    - { name: "healthify-backend" }
    - { name: "postgres" }
  args:
    warn: false

- name: Template production docker-compose file
  ansible.builtin.template:
    src: docker-compose.prod.yml.j2
    dest: /tmp/docker-compose.prod.yml
    mode: '0644'

- name: Deploy stack to Swarm via CLI
  become: true
  ansible.builtin.shell: |
    set -e
    if [ -z "{{ app_stack_name }}" ]; then
      echo "❌ app_stack_name is not defined"
      exit 1
    fi
    echo "Deploying stack: {{ app_stack_name }}"
    docker stack deploy -c /tmp/docker-compose.prod.yml {{ app_stack_name }}
  args:
    chdir: /tmp
    warn: false
