---
- name: Ensure Docker is running on all nodes
  hosts: all
  become: yes
  tasks:
    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

- name: Stop Healthify Stack and Remove Images
  hosts: manager
  become: yes
  tasks:
    - name: Remove existing Healthify stack (if any)
      shell: docker stack rm healthify
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Wait for Healthify stack removal to complete
      shell: |
        while docker stack services healthify 2>/dev/null | grep -q .; do
          echo "Waiting for Healthify stack to be removed..."
          sleep 10
        done
      args:
        executable: /bin/bash

    - name: Get image IDs for healthify-frontend
      shell: |
        {% raw %}
        docker images --format '{{"{{.Repository}} {{.ID}}"}}' | \
        grep '192.168.50.4:5000/healthify-frontend' | \
        awk '{print $2}'
        {% endraw %}
      register: frontend_images
      changed_when: false

    - name: Get image IDs for healthify-backend
      shell: |
        {% raw %}
        docker images --format '{{"{{.Repository}} {{.ID}}"}}' | \
        grep '192.168.50.4:5000/healthify-backend' | \
        awk '{print $2}'
        {% endraw %}
      register: backend_images
      changed_when: false

    - name: Combine image IDs
      set_fact:
        all_images: "{{ frontend_images.stdout_lines + backend_images.stdout_lines }}"

    - name: Remove Healthify images
      shell: docker rmi -f {{ item }}
      loop: "{{ all_images }}"
      when: all_images | length > 0
      ignore_errors: yes

- name: Deploy Healthify Stack from Manager
  hosts: manager
  become: yes
  tasks:
    - name: Create Healthify deployment directory
      file:
        path: /home/jenkins/healthify-stack
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'

    - name: Copy Healthify stack file to manager
      copy:
        src: ./stack/docker-stack.yml
        dest: /home/jenkins/healthify-stack/docker-stack.yml
        owner: jenkins
        group: jenkins
        mode: '0644'
        force: yes
        
    - name: Inject API URL into frontend config.js
      copy:
        dest: /home/jenkins/healthify-stack/config.js
        content: "export const API_BASE_URL = 'http://192.168.50.4:5050/api';"
        owner: jenkins
        group: jenkins
        mode: '0644'

    - name: Create external network healthify_net if not exists
      shell: docker network create --driver overlay healthify_net || true
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Ensure external volume pgdata exists
      shell: docker volume create pgdata || true
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Deploy Healthify stack
      shell: |
        set -a
        source /home/jenkins/healthify-stack/.env
        set +a
        docker stack deploy -c /home/jenkins/healthify-stack/docker-stack.yml healthify
      args:
        executable: /bin/bash
      register: deploy_result
      changed_when: "'Updating' in deploy_result.stdout or 'Creating' in deploy_result.stdout"
