---
- hosts: all
  become: true
  tasks:
    - name: Ensure Python + pip for Ansible
      apt:
        name:
          - python3
          - python3-pip
          - python3-distutils
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure packaging module
      pip:
        name: packaging
        state: latest
        executable: pip3
