global:
  scrape_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend"
    static_configs:
      - targets: ["backend:5050"]

  - job_name: "frontend"
    static_configs:
      - targets: ["frontend:5173"]

  - job_name: "node"
    dns_sd_configs:
      - names: ["tasks.node-exporter"]
        type: A
        port: 9100

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "cadvisor"
    dns_sd_configs:
      - names: ["tasks.cadvisor"]
        type: A
        port: 8080
