version: "3.2"

services:
  backend:
    image: 192.168.50.4:5000/healthify-backend:latest
    environment:
      PORT: 5050
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: healthify
      JWT_SECRET: healthify
      EXPIRES_IN: 24h
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    networks:
      - healthify_net

networks:
  healthify_net:
    external: true
