version: "3.2"

services:
  frontend:
    image: 192.168.50.4:5000/healthify-frontend:latest
    environment:
      - API_BASE_URL=http://192.168.50.4:5050/api/
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - healthify_net

networks:
  healthify_net:
    external: true
