services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: ingress
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - healthify_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: json-file

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - healthify_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: json-file

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - target: 9100
        published: 9100
        protocol: tcp
        mode: ingress
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - healthify_net
    logging:
      driver: json-file
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  postgres-exporter:
    image: wrouesnel/postgres_exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/healthify?sslmode=disable"
    ports:
      - target: 9187
        published: 9187
        protocol: tcp
        mode: ingress
    networks:
      - healthify_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: json-file

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - healthify_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: json-file

volumes:
  prometheus_data:
  grafana_data:

networks:
  healthify_net:
    external: true
